server:
  port: 3000
spring:
  application:
    name: springboot-jpa
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: c##keda
    password: root
  data: #ES配置  transport es 连接此为spring-data es的配置项
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: es-dev #(变动)
      cluster-nodes: 10.124.130.32:9200 #(变动)
      properties:
        transport:
          tcp:
            connect_timeout: 120s
  elasticsearch:  #ES配置 rest es 连接 此配置支持多数据源， 根据实际情况配置
    default-cluster: centos #(变动)
    datasource:
      dynamic:
        enable: true
    clusters:
      centos: #第一数据源
        rest-nodes: 10.124.130.32:9200
        thread-num: 10
        connect-timeout: 5000