server:
  port: 9999

spring:
  datasource: #数据库配置 根据实际数据库地址修改
    url: jdbc:mysql://localhost:3306/dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root #(变动)
    password: root# #(变动)
    driver-class-name: com.mysql.jdbc.Driver
demo:
  url: jdbc:mysql://192.168.1.1:3306
  username: root
  password: tomcat