server:
  port: 9999

spring:
  datasource: #数据库配置 根据实际数据库地址修改
    url: jdbc:mysql://10.165.78.7:24410/dev_smartmedia?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: dev_smartmedia #(变动)
    password: xiaofang119# #(变动)
    driver-class-name: com.mysql.jdbc.Driver
