server:
  port: 9998

spring:
  redis:
    cluster:
      nodes: localhost:6380,localhost:6381,localhost:6382
    database: 0
    pool:
      max-active: 8
      max-idle: 250
      max-wait: 2000
      min-idle: 0
      minEvictableIdleTime: 30000
      timeBetweenEviction: 30000
    testOnBorrow: true
    timeout: 5000
